name: Check for missing information
on: 
  issues:
    types: [opened]
jobs: 
  checkIssueInformation:
    name: Check for missing information
    runs-on: ubuntu-latest
    env:
      issue_incomplete: 'False'
    steps:
      - uses: actions/checkout@v2
      - name: Remove conflicting chars
        uses: frabert/replace-string-action@v1.2
        id: remove_quotations
        with:
          pattern: "\""
          string: ${{ github.event.issue.body }}
          replace-with: 'anyValue'
      - name: Check Information
        id: check-info
        run: echo "issue_incomplete=$(pwsh .\\.github\\scripts\\CheckIssueContent.ps1 "${{ steps.remove_quotations.outputs.replaced }}")" >> $GITHUB_ENV
      - name: Label Issue
        if: ${{env.issue_incomplete == 'True'}}
        run: |
          curl -v -u admin:${{ secrets.GITHUB_TOKEN }} -d '{"labels": ["needs more info"]}' ${{ github.event.issue.url }}/labels
        #uses: christianvuerings/add-labels@v1
        #with:
        #  labels: needs more info
        #env:
        #  issue_number: ${{ github.event.issue.number }}
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  - name: Ask for more information
    #    if: (env.output == true) #REVISAR
    #    uses: ben-z/actions-comment-on-issue@1.0.2
    #    with:
    #      message: "This issue is missing information. Please, make sure to fill in all the necessary fields."
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

