name: Check for missing information
on: 
  issues:
    types: [opened,edited]
jobs: 
  checkIssueInformation:
    name: Check for missing information
    runs-on: ubuntu-latest
    env:
      #The 'analysis_response' variable is used to store the script response on step one, 
      #and then checked on step two to know if adding the label and comment is necessary.
      #The initial 'undefined' value will be overridden when the script runs.
      analysis_response: undefined
      #issue_coment holds the comment format, while the missing information will be provided by analysis_response
      issue_comment: "This issue is missing information. Please, make sure to fill in all the necessary fields:"
      #template file name
      template: "ISSUE_TEMPLATE.md"
      #label to tag the issue with if its missing information
      issue_label: need more info
      #amount of sections from the template that can be missing information for the issue to still be considered complete
      acceptable_missing_info: 1
    steps:
      - uses: actions/checkout@v2
      - name: Remove conflicting chars
        uses: frabert/replace-string-action@v1.2
        id: remove_quotations
        with:
          pattern: "\""
          string: ${{ github.event.issue.body }}
          replace-with: '-'
      - name: Check Information
        id: check-info
        run: |
          ls -la
          echo "analysis_response=$(pwsh .\\.github\\scripts\\issue_analyzer.ps1 "${{ env.template }}" "${{ steps.remove_quotations.outputs.replaced }}" "${{ env.acceptable_missing_info }}" )" >> $GITHUB_ENV
      - name: Label and comment issue
        if: env.analysis_response != 'Valid'
        run: |
          curl -v -u admin:${{ secrets.GITHUB_TOKEN }} -d '{"labels": ["${{env.issue_label}}"]}' ${{ github.event.issue.url }}/labels
          curl -v -u admin:${{ secrets.GITHUB_TOKEN }} -d '{"body": "${{env.issue_comment}}${{env.analysis_response}}."}' ${{ github.event.issue.url }}/comments
      - name: Unlabel updated issue
        if: env.analysis_response == 'Valid'
        run: |
          echo urldecode ${{env.issue_label}}
          curl -v -u admin:${{ secrets.GITHUB_TOKEN }} -X DELETE ${{ github.event.issue.url }}/labels/$(echo -ne "${{env.issue_label}}" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
      - name: Clean Issue Body
        id: clean-issue-body
        run: |
          echo "parsed_issue_body=$(pwsh  .\\.github\\scripts\\issue_body_cleaner.ps1 "${{ github.event.issue.body }}" )"
      - name: checkout IssuesTypePredicter
        uses: actions/checkout@v2
        with:
          repository: RobertGlobant20/IssuesTypePredicter
      - name: Get Local Machine Information
        run: |
          pwd
          ls -R
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1   
      # restore dependencies  
      - name: Install dependencies
        run: dotnet restore
      - name: Run Issues Type Predicter
        run: | 
          cd "./IssuesTypePredicterML.ConsoleApp/bin/Release/netcoreapp3.1/"
          chmod +x ./IssuesTypePredicterML.exe
          ./IssuesTypePredicterML.exe
    
