name: Check for missing information
on: 
  issues:
    types: [opened]
jobs: 
  checkIssueInformation:
    name: Check for missing information
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove conflicting chars
        uses: frabert/replace-string-action@v1.2
        id: remove_quotations
        with:
          pattern: "\""
          string: ${{ github.event.issue.body }}
          replace-with: 'anyValue'
      - name: Check Information
        id: check-info
        run: echo "::set_output name=output::$(pwsh .\\.github\\scripts\\CheckIssueContent.ps1 "${{ steps.remove_quotations.outputs.replaced }}")"
      - name: Label ${{steps.check-info.outputs.output}} ISSUE
        run: ${{steps.check-info.outputs.output}}
      #  if: steps.id.outputs.key == 'True' #REVISAR
      #  uses: christianvuerings/add-labels@v1
      #  with:
      #    labels: needs more info
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  - name: Ask for more information
    #    if: (env.output == true) #REVISAR
    #    uses: ben-z/actions-comment-on-issue@1.0.2
    #    with:
    #      message: "This issue is missing information. Please, make sure to fill in all the necessary fields."
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

