name: Issues Actions Workflow

on: 
  issues:
    types: [opened]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      output: ""
    steps: 
      - name: Checkout Repo Content
        uses: actions/checkout@v2 #Check out the repository content
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: execute py script
        run: |
          output=$(python get_issues_info.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          echo "::set-output name=changelog::$output"
        id: run_python_script
      - name: Send Slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ steps.run_python_script.outputs.changelog }} 
      - name: Label Issues
        uses: github/issue-labeler@v2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          not-before: 2020-01-15T02:54:32Z
          enable-versioned-regex: 0
      - if: github.event.issue.body == ''
        name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Closed By: Not enought issue information.
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          #Literal body:
          body: A new issue has been created!
          to: roberto.tellez@globant.com
          from: aragontiger20@gmail.com # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
      #- name: Label Issues
       # uses: Naturalclar/issue-action@v2.0.2
        #with:
         # title-or-body: "both"
          #parameters: '[ {"keywords": ["bug", "error"], "labels": ["BUG"]}, {"keywords": ["help", "guidance"], "labels": ["help-wanted"]}]'
          #github-token: "${{ secrets.GITHUB_TOKEN }}"