name: Issues Actions Workflow

on: 
  issues:
    types: [opened]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      output: ""
    steps: 
      - name: Checkout Repo Content
        uses: actions/checkout@v2 #Check out the repository content
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: execute py script
        run: |
          output=$(python get_issues_info.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          echo "::set-output name=changelog::$output"
        id: run_python_script
      - name: Send Slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ steps.run_python_script.outputs.changelog }} 
      - name: Label Issues
        uses: github/issue-labeler@v2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          not-before: 2020-01-15T02:54:32Z
          enable-versioned-regex: 0
      - if: github.event.issue.body == ''
        name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Closed By: Not enought issue information.
      - name: Send email
        uses: AlexisMateo/sendmail-action@5
        with:
          smtp-server: smtp.gmail.com
          smtp-server-port: 587
          auth-user: ${{ secrets.MAIL_USERNAME }}
          auth-password: ${{ secrets.MAIL_PASSWORD }}
          subject: Testing GitHub Actions Email
          body: A new issue has been created!
          from: aragontiger20@gmail.com
          to: roberto.tellez@globant.com
          is-tls: true
