name: Issues Actions Workflow

on: 
  issues:
    types: [opened]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      output: ""
    steps: 
      - name: Checout Repo Content
        uses: actions/checkout@v2 #Check out the repository content
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: execute py script
        run: |
          echo "::set-output name=changelog::$(python get_issues_info.py)"
        id: run_python_script
      - name: Send Slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{join(steps.run_python_script.outputs.*, '\n')}} 