name: Create Issue on other repo V1

on: 
  issues:
    types: [opened]

jobs: 
  gitIssueCreation:
    if: contains(github.event.issue.labels.*.name, 'critical')
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - name: (Label bug) Move to astul repo
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id
        with:
          token: ${{ secrets.GIT_HUB_TOKEN3 }}
          owner: 'Astul-Betizagasti'
          repo: 'IssueTest'
          title: github.event.issue.title
          body: github.event.issue.body
      - name: (Label x) Move to roberto repo2
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id2
        with:
          token: ${{ secrets.GIT_HUB_TOKEN3 }}
          owner: 'RobertGlobant20'
          repo: 'issue_action2'
          title: github.event.issue.title
          body: github.event.issue.body
