name: Move Issue
on: 
  issues:
    types: [labeled]
env:
  MOVED: false
jobs: 
  gitIssueTransfer:
    strategy:
      matrix: 
        include: 
          - label: 'question'
            repoOwner: 'Astul-Betizagasti'
            repoName: 'IssueTest'
          - label: 'help-wanted'
            repoOwner: 'RobertGlobant20'
            repoName: 'issues_action2'
    name: Move issues to corresponding repository
    runs-on: ubuntu-latest
    steps:
      - name: (Label ${{ matrix.label }}) Move to ${{ matrix.repoName }}
        if: contains(github.event.issue.labels.*.name, matrix.label)
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id
        with:
          token: ${{ secrets.GIT_HUB_TOKEN3 }}
          owner: ${{ matrix.repoOwner }}
          repo: ${{ matrix.repoName }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
      - name: Close issue
        if: contains(github.event.issue.labels.*.name, matrix.label)
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            This issue will be moved to the ${{ matrix.repoOwner }}/${{ matrix.repoName }} repository.
            Auto-closing this issue.

