name: Create Issue on other repo

on: 
  issues:
    types: [labeled]

jobs: 
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git Creation Demo
        uses: bryannice/gitactions-git-issue-creation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_OWNER: 'RobertGlobant20'
          GITHUB_REPOSITORY: 'issues_action2'
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'