name: Move Issue
on: 
  issues:
    types: [labeled]

jobs: 
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - name: (Label bug) Move to astul repo
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id
        with:
          token: ${{ secrets.GIT_HUB_TOKEN3 }}
          owner: 'Astul-Betizagasti'
          repo: 'IssueTest'
          title: github.event.issue.title
          body: github.event.issue.body
      - name: (Label critical) Move to roberto repo2
        if: contains(github.event.issue.labels.*.name, 'critical')
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id2
        with:
          token: ${{ secrets.GIT_HUB_TOKEN3 }}
          owner: 'RobertGlobant20'
          repo: 'issues_action2'
          title: github.event.issue.title
          body: github.event.issue.body
