name: Create Issue on other repo V1

on: 
  issues:
    types: [labeled]

jobs: 
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id
        with:
          token: ${{ secrets.GITHUB_TOKEN2 }}
          owner: 'Astul-Betizagasti'
          repo: 'IssueTest'
          title: 'Issue sent from other repo'
          body: 'Body content yeh'
      - name: Print outputs
        run: |
          echo ${{ steps.my_step_id.outputs.id }}
          echo ${{ steps.my_step_id.outputs.number }}